apiVersion: v1
kind: Service
metadata:
  name: wefox-service
spec:
  type: LoadBalancer
  selector:
    app: wefox-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wefox-hello
  labels:
    app: wefox-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wefox-hello
  template:
    metadata:
      labels:
        app: wefox-hello
    spec:
      containers:
      - name: wefox-hello
        image: docker.io/hashicorp/http-echo
        ports:
        - containerPort: 5678
        args: ["-text=hello world"]